version: "3.7"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"  # Porta HTTP do Jellyfin
      - "8920:8920"  # Porta HTTPS do Jellyfin
    volumes:
      - /mnt/hdvideos:/media  # Pasta onde estão os vídeos
      - jellyfin_config:/config
      - jellyfin_cache:/cache
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    networks:
      - network_public
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`streaming.seudominio.com`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls.certresolver=letsencryptresolver
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

volumes:
  jellyfin_config:
  jellyfin_cache:

networks:
  network_public:
    external: true
    name: network_public
