version: "3.7"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - network_public
    volumes:
      - /mnt/hdvideos:/media  # Apenas a pasta de vídeos no HD
      - jellyfin_config:/config
      - jellyfin_cache:/cache
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`streaming.seudominio.com`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls.certresolver=letsencryptresolver
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.services.jellyfin.loadbalancer.passHostHeader=true
      - traefik.http.routers.jellyfin.middlewares=jellyfin-stripprefix,jellyfin-https-redirect
      - traefik.http.middlewares.jellyfin-stripprefix.stripprefix.prefixes=/
      - traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https
      - traefik.http.services.jellyfin.loadbalancer.server.scheme=http
      - traefik.http.services.jellyfin.loadbalancer.server.insecureSkipVerify=true
      - traefik.docker.network=network_public  # Garantir que está na rede do Traefik

volumes:
  jellyfin_config:
  jellyfin_cache:

networks:
  network_public:
    external: true
    name: network_public
