version: "3.7"

services:
  postgres:
    image: postgres:16
    command: [postgres, --max_connections=200]
    environment:
      - POSTGRES_PASSWORD=SENHA
    networks:
      - network_public
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks:
  network_public:
    external: true
    name: network_public
