version: "3.7"
services:
  redis:
    image: redis:7
    networks:
      - network_public
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --port 6379
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker
      resources:
        limits:
          cpus: "1"
          memory: 1024M
volumes:
  redis_data:
    external: true
    name: redis_data
networks:
  network_public:
    external: true
    name: network_public
